spring.kafka.bootstrap-servers=localhost:30092
spring.cassandra.contact-points=127.0.0.1
spring.cassandra.port=30942
spring.cassandra.request.timeout=30s
spring.cassandra.connection.init-query-timeout=30s
